MYSQL_DATABASE=notesdb
MYSQL_USER=shankar
MYSQL_PASSWORD=makemusic
MYSQL_HOST=db
MYSQL_PORT=3306
DJANGO_SECRET_KEY=changeme-in-prod

# error

#   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

#     return func(*args, **kwargs)

#   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

#     self.connect()

#   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__

#     raise dj_exc_value.with_traceback(traceback) from exc_value

#   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

#     self.connect()

#   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

#     return func(*args, **kwargs)

#   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect

#     self.connection = self.get_new_connection(conn_params)

#   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner

#     return func(*args, **kwargs)

#   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection

#     connection = Database.connect(**conn_params)

#   File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 121, in Connect

#     return Connection(*args, **kwargs)

#   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 195, in __init__

#     super().__init__(*args, **kwargs2)

# django.db.utils.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (115)")